### ISSUE TITLE
Merging with sideline-lsp?

### ISSUE THREAD

**Issue by DevelopmentCool2449** [emacs-sideline/sideline-eglot#4]
Hello, i was wondering if it's a good idea merging this package to sideline-lsp, 
My idea is sharing variables and functions from both packages and allow to users
choose if they prefer use lsp or eglot backends.

If you agree, i would like helping making a PR to sideline-lsp implementing all features (and fixes)
of this package.

**Comment by jcs090218** [comment]
It depends on how much code we can share between the two. From the implementation perspective, Lsp-mode and Eglot have very different implementations, so in general, my answer is no. 

We might also want to take dependencies management into account since Eglot is built-in now, but Lsp-mode remains as an external package.

Furthermore, merging two backends may defeat the purpose of letting users customize their backends.

**Comment by DevelopmentCool2449** [comment]
> Furthermore, merging two backends may defeat the purpose of letting users customize their backends.

You are right, I find that keeping those 2 packages separate is a better idea, 
I'm closing this.
